spring.application.name=tcltravels

# Connection Settings
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tcltravels}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}

# Initialization Logic
# This ensures Spring Boot runs your schema.sql on startup
spring.sql.init.mode=always

# This prevents Hibernate from trying to create its own tables
# so that your manual SQL remains the "Source of Truth"
spring.jpa.hibernate.ddl-auto=none

# Logging - This will print the SQL being executed to your console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
