DROP TABLE IF EXISTS auctions CASCADE;
DROP TABLE IF EXISTS reservation_passengers CASCADE;
DROP TABLE IF EXISTS legs CASCADE;
DROP TABLE IF EXISTS reservations CASCADE;
DROP TABLE IF EXISTS passengers CASCADE;
DROP TABLE IF EXISTS customer_preferences CASCADE;
DROP TABLE IF EXISTS fares CASCADE;
DROP TABLE IF EXISTS stops_at CASCADE;
DROP TABLE IF EXISTS flights CASCADE;
DROP TABLE IF EXISTS advance_purchase_discounts CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS app_users CASCADE;
DROP TABLE IF EXISTS persons CASCADE;
DROP TABLE IF EXISTS airports CASCADE;
DROP TABLE IF EXISTS airlines CASCADE;

CREATE TABLE airlines (
  id CHAR(2) NOT NULL CHECK (id ~ '^[A-Z]{2}$'),
  name TEXT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE airports (
  id CHAR(3) NOT NULL CHECK (id ~ '^[A-Z]{3}$'),
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  country TEXT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE persons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  address TEXT,
  city TEXT,
  state CHAR(2),
  zip_code INTEGER NOT NULL CHECK (
    zip_code BETWEEN 10000
    AND 99999
  ),
  telephone TEXT NOT NULL CHECK (telephone ~ '^\d{10,11}$'),
  PRIMARY KEY (id)
);

CREATE TABLE app_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL UNIQUE CHECK (username !~ '^\s*$'),
  password TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('CUSTOMER', 'EMPLOYEE', 'MANAGER')),
  person_id BIGINT NOT NULL UNIQUE,
  PRIMARY KEY(id),
  FOREIGN KEY(person_id) REFERENCES persons(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  account_id BIGINT NOT NULL UNIQUE,
  creation_date TIMESTAMPTZ,
  rating INTEGER,
  PRIMARY KEY (id),
  FOREIGN KEY (account_id) REFERENCES app_users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  account_id BIGINT NOT NULL UNIQUE,
  ssn INTEGER NOT NULL UNIQUE CHECK (
    ssn BETWEEN 100000000
    AND 999999999
  ),
  start_date DATE,
  hourly_rate NUMERIC(10, 2),
  PRIMARY KEY (id),
  FOREIGN KEY (account_id) REFERENCES app_users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE flights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  airline_id CHAR(2) NOT NULL,
  flight_number INTEGER NOT NULL,
  number_of_seats INTEGER NOT NULL CHECK (number_of_seats > 0),
  days_operating CHAR(7) NOT NULL,
  min_length_stay INTEGER DEFAULT 0,
  max_length_stay INTEGER,
  origin_airport_id CHAR(3) NOT NULL,
  destination_airport_id CHAR(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (airline_id, flight_number),
  FOREIGN KEY (airline_id) REFERENCES airlines(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (origin_airport_id) REFERENCES airports(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (destination_airport_id) REFERENCES airports(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE stops_at (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  flight_id BIGINT NOT NULL,
  stop_number INTEGER NOT NULL,
  airport_id CHAR(3) NOT NULL,
  arrival_time TIMESTAMPTZ,
  departure_time TIMESTAMPTZ,
  arrival_delay INTEGER,
  departure_delay INTEGER,
  PRIMARY KEY (id),
  UNIQUE (flight_id, stop_number),
  UNIQUE (flight_id, airport_id),
  FOREIGN KEY (flight_id) REFERENCES flights(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (airport_id) REFERENCES airports(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE fares (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  flight_id BIGINT NOT NULL,
  fare_type INTEGER NOT NULL,
  class TEXT NOT NULL,
  fare NUMERIC(10, 2) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (flight_id, fare_type, class),
  FOREIGN KEY (flight_id) REFERENCES flights(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE advance_purchase_discounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  airline_id CHAR(2) NOT NULL,
  days INTEGER NOT NULL,
  discount_rate NUMERIC(5, 2),
  PRIMARY KEY (id),
  UNIQUE (airline_id, days),
  FOREIGN KEY (airline_id) REFERENCES airlines(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  reservation_date TIMESTAMPTZ,
  booking_fee NUMERIC(10, 2),
  total_fare NUMERIC(10, 2),
  employee_id BIGINT,
  customer_id BIGINT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE legs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  reservation_id BIGINT NOT NULL,
  leg_number INTEGER NOT NULL,
  flight_id BIGINT NOT NULL,
  from_stop_number INTEGER,
  PRIMARY KEY (id),
  UNIQUE (reservation_id, leg_number),
  FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (flight_id) REFERENCES flights(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE passengers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  customer_id BIGINT NOT NULL,
  passenger_name TEXT,
  PRIMARY KEY (id),
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE reservation_passengers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  reservation_id BIGINT NOT NULL,
  passenger_id BIGINT NOT NULL,
  seat_number INTEGER,
  class TEXT,
  meal TEXT,
  PRIMARY KEY (id),
  UNIQUE (reservation_id, passenger_id),
  FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (passenger_id) REFERENCES passengers(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE customer_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  customer_id BIGINT NOT NULL,
  preference TEXT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (customer_id, preference),
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE auctions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  customer_id BIGINT NOT NULL,
  flight_id BIGINT NOT NULL,
  class TEXT,
  date DATE,
  name_your_own_price NUMERIC(10, 2) NOT NULL,
  accepted BOOLEAN,
  PRIMARY KEY (id),
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (flight_id) REFERENCES flights(id) ON UPDATE CASCADE ON DELETE CASCADE
);
