DROP TABLE IF EXISTS airlines CASCADE;

DROP TABLE IF EXISTS advance_purchase_discounts CASCADE;

DROP TABLE IF EXISTS flights CASCADE;

DROP TABLE IF EXISTS airports CASCADE;

DROP TABLE IF EXISTS stops_at CASCADE;

DROP TABLE IF EXISTS fares CASCADE;

DROP TABLE IF EXISTS persons CASCADE;

DROP TABLE IF EXISTS app_users CASCADE;

DROP TABLE IF EXISTS customers CASCADE;

DROP TABLE IF EXISTS customer_preferences CASCADE;

DROP TABLE IF EXISTS employees CASCADE;

DROP TABLE IF EXISTS passengers CASCADE;

DROP TABLE IF EXISTS reservations CASCADE;

DROP TABLE IF EXISTS legs CASCADE;

DROP TABLE IF EXISTS reservation_passengers CASCADE;

DROP TABLE IF EXISTS auctions CASCADE;

CREATE TABLE airlines (
  id CHAR(2) NOT NULL,
  name TEXT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE advance_purchase_discounts (
  airline_id CHAR(2),
  days INTEGER,
  discount_rate NUMERIC(5, 2),
  PRIMARY KEY (airline_id, days),
  FOREIGN KEY (airline_id) REFERENCES airlines(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE flights (
  airline_id CHAR(2) NOT NULL,
  flight_number INTEGER NOT NULL,
  number_of_seats INTEGER NOT NULL CHECK (number_of_seats > 0),
  days_operating CHAR(7) NOT NULL,
  min_length_stay INTEGER DEFAULT 0,
  max_length_stay INTEGER,
  PRIMARY KEY (airline_id, flight_number),
  FOREIGN KEY (airline_id) REFERENCES airlines(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE airports (
  id CHAR(3) NOT NULL,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  country TEXT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE stops_at (
  airline_id CHAR(2),
  flight_number INTEGER,
  stop_number INTEGER,
  airport_id CHAR(3),
  arrival_time TIMESTAMPTZ,
  departure_time TIMESTAMPTZ,
  arrival_delay INTEGER,
  departure_delay INTEGER,
  PRIMARY KEY (airline_id, flight_number, stop_number),
  UNIQUE (airline_id, flight_number, airport_id),
  FOREIGN KEY (airline_id, flight_number) REFERENCES flights(airline_id, flight_number) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (airport_id) REFERENCES airports(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE fares (
  airline_id CHAR(2),
  flight_number INTEGER,
  fare_type INTEGER,
  class TEXT,
  fare NUMERIC(10, 2),
  PRIMARY KEY (airline_id, flight_number, fare_type, class),
  FOREIGN KEY (airline_id, flight_number) REFERENCES flights(airline_id, flight_number) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE persons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  address TEXT,
  city TEXT,
  state TEXT,
  zip_code INTEGER NOT NULL,
  telephone TEXT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE app_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  person_id BIGINT,
  PRIMARY KEY(id),
  FOREIGN KEY(person_id) REFERENCES persons(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE customers (
  id BIGINT,
  account_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  credit_card_number CHAR(16) NOT NULL,
  email TEXT NOT NULL,
  creation_date TIMESTAMPTZ,
  rating INTEGER,
  PRIMARY KEY (account_number),
  FOREIGN KEY (id) REFERENCES persons (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE customer_preferences (
  account_number BIGINT,
  preference TEXT,
  PRIMARY KEY (account_number, preference),
  FOREIGN KEY(account_number) REFERENCES customers (account_number) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE employees (
  id BIGINT,
  ssn INTEGER NOT NULL,
  is_manager BOOLEAN,
  start_date DATE,
  hourly_rate NUMERIC(10, 2),
  PRIMARY KEY (ssn),
  FOREIGN KEY (id) REFERENCES persons (id) ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE (id)
);

CREATE TABLE passengers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  account_number BIGINT,
  passenger_name TEXT,
  PRIMARY KEY (id),
  FOREIGN KEY(account_number) REFERENCES customers (account_number) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE reservations (
  reservation_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  reservation_date TIMESTAMPTZ,
  booking_fee NUMERIC(10, 2),
  total_fare NUMERIC(10, 2),
  employee_ssn INTEGER,
  account_number BIGINT,
  PRIMARY KEY (reservation_number),
  FOREIGN KEY (employee_ssn) REFERENCES employees (ssn) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (account_number) REFERENCES customers (account_number) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE legs (
  reservation_number BIGINT,
  leg_number INTEGER,
  airline_id CHAR(2),
  flight_number INTEGER,
  from_stop_number INTEGER,
  PRIMARY KEY (reservation_number, leg_number),
  FOREIGN KEY (reservation_number) REFERENCES reservations (reservation_number) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (airline_id, flight_number) REFERENCES flights (airline_id, flight_number) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (airline_id, flight_number, from_stop_number) REFERENCES stops_at (airline_id, flight_number, stop_number) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE reservation_passengers (
  reservation_number BIGINT,
  passenger_id BIGINT,
  account_number BIGINT,
  seat_number INTEGER,
  class TEXT,
  meal TEXT,
  PRIMARY KEY (reservation_number, passenger_id, account_number),
  FOREIGN KEY (reservation_number) REFERENCES reservations (reservation_number) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (passenger_id) REFERENCES passengers (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE auctions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  account_number BIGINT,
  airline_id CHAR(2),
  flight_number INTEGER,
  class TEXT,
  date DATE,
  name_your_own_price NUMERIC(10, 2) NOT NULL,
  accepted BOOLEAN,
  PRIMARY KEY (id),
  FOREIGN KEY (account_number) REFERENCES customers(account_number) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (airline_id, flight_number) REFERENCES flights(airline_id, flight_number) ON UPDATE CASCADE ON DELETE CASCADE
);